### ISSUE TITLE
Update levelup rules

### ISSUE THREAD

**Issue by MNoya** [MNoya/PMP#22]
Double XP_PER_PEON, from 10 to 20

Suggested by https://moddota.com/forums/discussion/1638/suggestion-more-faster-levels-in-pmp

**Comment by insunaa** [comment]
Related to that, I think that health regen is a bit too powerful right now, so much so that Humans are the only viable option in lategame. Even with all damage skills and weapon upgrades, health regeneration often prevents peons to kill one another in 1 on 1 fights, as all damage from the first hit is regenerated by the time the second hit lands. Humans get around this problem because their racial allows them to instakill with every ~~fourth~~ fifth hit.

Personally I think it'd be best if health regen would be capped to 10 upgrades instead of 20 right now. This still makes it devastatingly powerful, but it increases the viability of most races in the lategame by a lot. Right now only humans and goblins are viable (because goblins can afford to spend unholy amounts of gold to build armies of 40+ goblin peons and if the humans are permastunned by superior numbers, they can't instakill)

**Comment by MNoya** [comment]
Implemented both ideas!
